/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sanjevani.view;

import com.sanjevani.database.Database;
import com.sanjevani.model.Encounter;
import com.sanjevani.model.Person;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajatsharma
 */
public class DoctorHome extends javax.swing.JFrame {

    /**
     * Creates new form DoctorHome
     */
    
    private String[] tableColumns = {"Patient Name", "Age", "Gender", "Date of Encounter", "Status"};
    

    public DoctorHome() {
        initComponents();
        setEncounterTable(new ArrayList<Encounter>(Database.encounterList.values()));
    }

    
    private void setEncounterTable(List<Encounter> encounterList) {
        int row = 0;
        String[][] tableContent = new String[encounterList.size()][5];
        
        for (Encounter encounterInstance : encounterList) {            
            Person patientInstance = Database.personList.get(encounterInstance.getPatientId());
            tableContent[row][0] = patientInstance.getName();
            tableContent[row][1] = String.valueOf(patientInstance.getAge());
            tableContent[row][2] = patientInstance.getGender();
            tableContent[row][3] = encounterInstance.getDateOfEncounter();
            tableContent[row][4] = encounterInstance.getStatus();
            row++;
        }

        encounterTable.setModel(new DefaultTableModel(tableContent, tableColumns));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encounterDetail = new javax.swing.JPanel();
        viewEncounters = new javax.swing.JPanel();
        encounterTableScrollPanel = new javax.swing.JScrollPane();
        encounterTable = new javax.swing.JTable();

        encounterDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Encounter Details"));

        javax.swing.GroupLayout encounterDetailLayout = new javax.swing.GroupLayout(encounterDetail);
        encounterDetail.setLayout(encounterDetailLayout);
        encounterDetailLayout.setHorizontalGroup(
            encounterDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        encounterDetailLayout.setVerticalGroup(
            encounterDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        viewEncounters.setBorder(javax.swing.BorderFactory.createTitledBorder("Encounter List"));

        encounterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        encounterTableScrollPanel.setViewportView(encounterTable);

        javax.swing.GroupLayout viewEncountersLayout = new javax.swing.GroupLayout(viewEncounters);
        viewEncounters.setLayout(viewEncountersLayout);
        viewEncountersLayout.setHorizontalGroup(
            viewEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewEncountersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encounterTableScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
        );
        viewEncountersLayout.setVerticalGroup(
            viewEncountersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewEncountersLayout.createSequentialGroup()
                .addComponent(encounterTableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewEncounters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encounterDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encounterDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewEncounters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel encounterDetail;
    private javax.swing.JTable encounterTable;
    private javax.swing.JScrollPane encounterTableScrollPanel;
    private javax.swing.JPanel viewEncounters;
    // End of variables declaration//GEN-END:variables
}
