/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sanjevani.view;

import com.sanjevani.database.Database;
import com.sanjevani.model.Community;
import com.sanjevani.model.House;
import com.sanjevani.model.Person;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajatsharma
 */
public class PeoplePanel extends javax.swing.JPanel {
    int selectedPersonId;
    List<Integer> communityKeyList = new ArrayList<>();
    /**
     * Creates new form HospitalsPanel
     */
    public PeoplePanel() {
        initComponents();
        setPeopleTable();
        initializePeopleView();
    }
    
    private void initializePeopleView() {
        // Populate Roles
        DefaultComboBoxModel roleModel = new DefaultComboBoxModel();
        roleModel.removeAllElements();
        roleModel.addElement("--Select--");
        
        for(String role: Database.roles) {
            roleModel.addElement(role);
        }
        
        roleComboBox.setModel(roleModel);

        // Populate Communities
        DefaultComboBoxModel communityModel = new DefaultComboBoxModel();
        communityModel.removeAllElements();
        communityModel.addElement("--Select--");
        
        Database.communityList.forEach((key, community) -> {
            communityKeyList.add(key);
            communityModel.addElement(community.getCommunityName());
        });
        
        communityComboBox.setModel(communityModel);
        
        // hide update and delete btn
        updateBtn.setVisible(false);
        deleteBtn.setVisible(false);
    }
    
    private void resetPersonForm() {
        personNameTxt.setText("");
        emailIdTxt.setText("");
        passwordTxt.setText("");
        ageTxt.setText("");
        roleComboBox.setSelectedIndex(0);
        genderComboBox.setSelectedIndex(0);
        houseTxt.setText("");
        communityComboBox.setSelectedIndex(0);
        peopleTable.getSelectionModel().clearSelection();
        
        updateBtn.setVisible(false);
        deleteBtn.setVisible(false);
        
        // Hide ID column
        peopleTable.getColumnModel().getColumn(0).setMinWidth(0);
        peopleTable.getColumnModel().getColumn(0).setMaxWidth(0);
        peopleTable.getColumnModel().getColumn(0).setWidth(0);
    }
    
    private void setPeopleTable() {
        HashMap<Integer,Person> list = Database.personList;
        String[] tableColumns = {"Id", "Person Name", "EmailId","Age", "Gender", "Role", "House", "Community Name", "City Name", "Zip Code"};
        String[][] tableContent = new String[list.size()][tableColumns.length];

        int key = 0;
        
        for(Map.Entry<Integer, Person> entry: list.entrySet()) {
            Person person = entry.getValue();
            tableContent[key][0] = String.valueOf(person.getPersonId());
            tableContent[key][1] = person.getEmailId();
            tableContent[key][2] = person.getName();
            tableContent[key][3] = String.valueOf(Database.personList.get(person.getPersonId()).getAge());
            tableContent[key][4] = Database.personList.get(person.getPersonId()).getGender();
            tableContent[key][5] = Database.personList.get(person.getPersonId()).getRole();
            House house = Database.houseList.get(person.getHouseId());
            
            tableContent[key][6] = house.getAddress();
            
            Community community = Database.communityList.get(house.getCommunityId());
            tableContent[key][7] = community.getCommunityName();            
            tableContent[key][8] = Database.cityList.get(community.getCityId()).getCityName();
            tableContent[key][9] = String.valueOf(community.getZipcode());
            key++;
        }
        
        peopleTable.setModel(new DefaultTableModel(tableContent, tableColumns));
        resetPersonForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PeopleOuterPanel = new javax.swing.JPanel();
        AddPeoplePanel = new javax.swing.JPanel();
        personNameLabel = new javax.swing.JLabel();
        personNameTxt = new javax.swing.JTextField();
        emailIdLabel = new javax.swing.JLabel();
        emailIdTxt = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        roleLabel = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        houseLabel = new javax.swing.JLabel();
        houseTxt = new javax.swing.JTextField();
        communityLabel = new javax.swing.JLabel();
        communityComboBox = new javax.swing.JComboBox<>();
        buttonPanel = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        scrollTablePanel = new javax.swing.JScrollPane();
        peopleTable = new javax.swing.JTable();

        PeopleOuterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage People"));
        PeopleOuterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPeoplePanel.setLayout(new java.awt.GridLayout(8, 2));

        personNameLabel.setText("Name");
        AddPeoplePanel.add(personNameLabel);
        AddPeoplePanel.add(personNameTxt);

        emailIdLabel.setText("EmailID");
        AddPeoplePanel.add(emailIdLabel);
        AddPeoplePanel.add(emailIdTxt);

        passwordLabel.setText("Password");
        AddPeoplePanel.add(passwordLabel);

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        AddPeoplePanel.add(passwordTxt);

        ageLabel.setText("Age");
        AddPeoplePanel.add(ageLabel);
        AddPeoplePanel.add(ageTxt);

        roleLabel.setText("Role");
        AddPeoplePanel.add(roleLabel);

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AddPeoplePanel.add(roleComboBox);

        genderLabel.setText("Gender");
        AddPeoplePanel.add(genderLabel);

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Male", "Female" }));
        AddPeoplePanel.add(genderComboBox);

        houseLabel.setText("House");
        AddPeoplePanel.add(houseLabel);
        AddPeoplePanel.add(houseTxt);

        communityLabel.setText("Community");
        AddPeoplePanel.add(communityLabel);

        communityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AddPeoplePanel.add(communityComboBox);

        PeopleOuterPanel.add(AddPeoplePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 19, 900, 360));

        buttonPanel.setLayout(new java.awt.GridLayout(1, 0));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(updateBtn);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(addBtn);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(resetBtn);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        buttonPanel.add(deleteBtn);

        PeopleOuterPanel.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 900, 60));

        peopleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        peopleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peopleTableMouseClicked(evt);
            }
        });
        scrollTablePanel.setViewportView(peopleTable);

        PeopleOuterPanel.add(scrollTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 458, 900, 439));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PeopleOuterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PeopleOuterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void peopleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peopleTableMouseClicked
        selectedPersonId = Integer.parseInt(peopleTable.getValueAt(peopleTable.getSelectedRow(), 0 ).toString());

        Person selectedItem = Database.personList.get(selectedPersonId);

        personNameTxt.setText(selectedItem.getName());
        emailIdTxt.setText(selectedItem.getEmailId());
        passwordTxt.setText(selectedItem.getPassword());
        ageTxt.setText(String.valueOf(selectedItem.getAge()));
        genderComboBox.setSelectedItem(selectedItem.getGender());
        roleComboBox.setSelectedItem(selectedItem.getRole());
        
        House house = Database.houseList.get(selectedItem.getHouseId());
        
        houseTxt.setText(house.getAddress());
        
        Community community = Database.communityList.get(house.getCommunityId());
        communityComboBox.setSelectedItem(community.getCommunityName());
        
        // Hide and Show Button
        updateBtn.setVisible(true);
        deleteBtn.setVisible(true);
    }//GEN-LAST:event_peopleTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        Person selectedPerson = Database.personList.get(selectedPersonId);
        selectedPerson.setName(personNameTxt.getText());
        selectedPerson.setEmailId(emailIdTxt.getText());
        selectedPerson.setPassword(passwordTxt.getText());
        selectedPerson.setAge(Integer.parseInt(ageTxt.getText()));
        selectedPerson.setRole(roleComboBox.getSelectedItem().toString());
        selectedPerson.setGender(genderComboBox.getSelectedItem().toString());
        
        House selectedPersonHouse = Database.houseList.get(selectedPerson.getHouseId());
        selectedPersonHouse.setAddress(houseTxt.getText());
        
        int communityId = communityKeyList.get(communityComboBox.getSelectedIndex()-1);
        selectedPersonHouse.setCommunityId(communityId);
        
        setPeopleTable();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int communityId = communityKeyList.get(communityComboBox.getSelectedIndex()-1);
        Database.createHouse(communityId, houseTxt.getText());

        // TODO: Fix lasthouseID
        Database.createAdmin(
                personNameTxt.getText(),
                emailIdTxt.getText(),
                passwordTxt.getText(),
                roleComboBox.getSelectedItem().toString(),
                Integer.parseInt(ageTxt.getText()),
                genderComboBox.getSelectedItem().toString(),
                Database.lastHouseId-1
        );
        setPeopleTable();
    }//GEN-LAST:event_addBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        resetPersonForm();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        Database.personList.remove(selectedPersonId);
        setPeopleTable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPeoplePanel;
    private javax.swing.JPanel PeopleOuterPanel;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> communityComboBox;
    private javax.swing.JLabel communityLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel emailIdLabel;
    private javax.swing.JTextField emailIdTxt;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel houseLabel;
    private javax.swing.JTextField houseTxt;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTable peopleTable;
    private javax.swing.JLabel personNameLabel;
    private javax.swing.JTextField personNameTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JScrollPane scrollTablePanel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
